#!/usr/bin/env node

let colors = require('colors');
let readline = require('readline-sync');
let path = require('path');
let fs = require('fs');
let release = false;
let brewster = require('../index');

let error = function(str) {
    console.log('ERROR! '.red + str);
}

/* Log Brewster info on startup. */
console.log(('[' + (release ? 'RELEASE'.green : 'DEV'.red) + ']') + ' Brewster ' + require('../package.json').version);
console.log('Copyright (c) RevelMind 2020');

//console.log(brewster.getPackages());

while(true) {
    let cmd = readline.question(brewster.getCWD().green + ' ~$ ').trim();

    if(cmd == '') {
        error('Invalid command.');
    } else {
        let all = cmd.split(' ');
        let cmdName = all[0];
        let cmdArgs = [];

        if(all.length > 1) {
            cmdArgs = all.slice(1);
        }

        let packages = brewster.getPackages();
        let package = brewster.getPackage(cmdName);

        if(package) {
            if(package.package.onCommand) {
                package.package.onCommand(cmdArgs);
            }
        }
    }
}